# Generated by Django 5.2.10 on 2026-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsdtransmissionlog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zatcainvoicelog",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
